algoritmo "Soma Numeros"
// Função :
// Autor :
// Data : 20/05/2020
// Seção de Declarações 
var
n1 , n2 , soma: Real

inicio
// Seção de Comandos 

Escreval ("Bem-vindo a sua calculadora!")
Escreval("Informe um numero: ")
Leia(n1)
Escreval("Informe outro numero : ")
leia(n2)
soma <- n1+n2
escreval("O resultado é : ", soma)

escreval ("O resultado da soma de ", n1, " e ", n2, " é :" , soma)
fimalgoritmo
